# This workflow will install Kotlin dependencies and run tests

name: Kotlin Checks

defaults:
  run:
    working-directory: ./kotlin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Tests
      run: |
        ./gradlew --info check
